FORMAT: 1A


# CallSquad Contacts
Welcome to the CallSquad Contacts DRAFT API v1 developer documentation!

Please note this documentation is a Work In Progress and the API isn't complete.

## Authentication

![OAuth 2.0](http://oauth.net/images/oauth-2-sm.png)

The CallSquad Contacts API uses [OAuth 2.0](http://oauth.net/2/) for authentication. You will first need to get an application key from CallSquad. The CallSquad Contacts API uses the Authorization Code flow to get access tokens and refresh tokens.

Once registered use the following endpoints to get your Access and Refresh tokens using the keys provided by CallSquad:

* `Authorization URL` https://contacts.callsquad.com/oauth/authorize
* `Access Token URL` https://contacts.callsquad.com/oauth/access_token
* `Refresh Token URL` https://contacts.callsquad.com/oauth/access_token


## Campaigns [/campaigns]

### List all Campaigns [GET]
+ Request (application/json)

    + Headers

            Authorization: Bearer someRandomAccessToken

+ Response 200 (application/json)

    + Body

            [
                {
                    "campaignId" : "53ab2290c55bdbacf7984d9f"
                    "name" : "Campaign Name"
                },
                {
                    "campaignId" : "53ab2290c55bdbacf7984d9e"
                    "name" : "Another Campaign Name"
                }
            ]

## Contacts [/Contacts/{campaignId}]

+ Parameters
    + campaignId (required, string, `53ab2290c55bdbacf7984d9e`) ... The ID of the campaign.

### List all Contacts for Campaign [GET]

The number of contacts are returned is limited to 1000 per page.

+ Request (application/json)

    + Headers

            Authorization: Bearer someRandomAccessToken

+ Response 200 (application/json)

    + Body

            {
                "contacts" : [
                    {
                        "id": "5502c598a6427fe74caa6def",
                        "userRef" : "youruserid",
                        "firstName": "John",
                        "lastName": "Doe",
                        "valid": true,
                        "phoneCountryCode": "GB",
                        "phoneNumber": "07891011121",
                        "timezone": "Europe/London",
                        "jobTitle": "regional manager",
                        "company": "SkyPower",
                        "callCount": 0,
                        "lastContacted": null,
                        "lastOutcome": null,
                        "email": "me@email.com"
                    },
                    {
                        "id": "5502c598a6427fe74caa6def",
                        "userRef" : "youruserid",
                        "firstName": "Jane",
                        "lastName": "Doe",
                        "valid": true,
                        "phoneCountryCode": "GB",
                        "phoneNumber": "07891011122",
                        "timezone": "Europe/London",
                        "jobTitle": "regional manager",
                        "company": "SkyPower",
                        "callCount": 1,
                        "lastContacted": "2015-03-13T11:10:16.981Z",
                        "lastOutcome": 7,
                        "email": "me@email.com"
                    }
                ],
                "pagination": {
                    "total": 2,
                    "count": 2,
                    "per_page": 1000,
                    "current_page": 1,
                    "total_pages": 1,
                    "links": {
                        "next": "https:\/\/contacts.callsquad.com\/api\/v1\/contacts\/53ab2290c55bdbacf7984d9e\/?page=2"
                    }
                }
            }

### Add contacts to a campaign [POST]
Your userRef must be unique accross all campaigns, this is an optional field.

+ Request (application/json)

    + Headers

            Authorization: Bearer someRandomAccessToken

    + Body

            [
                {
                    "userRef" : "youruserid1",
                    "firstName": "Jane",
                    "lastName": "Doe",
                    "phoneCountryCode": "GB",
                    "phoneNumber": "07891011122",
                    "timezone": "Europe/London",
                    "jobTitle": "regional manager",
                    "company": "SkyPower",
                    "email": "me@email.com"
                },
                {
                    "userRef" : "youruserid2",
                    "firstName": "John",
                    "lastName": "Doe",
                    "phoneCountryCode": "GB",
                    "phoneNumber": "07891011121",
                    "timezone": "Europe/London",
                    "jobTitle": "regional manager",
                    "company": "SkyPower",
                    "email": "me@email.com"
                }
            ]

+ Response 200 (application/json)

    + Body

            {
                "contacts" : [
                    {
                        "id": "5502c598a6427fe74caa6def",
                        "userRef" : "youruserid1",
                        "firstName": "John",
                        "lastName": "Doe",
                        "valid": true,
                        "phoneCountryCode": "GB",
                        "phoneNumber": "07891011121",
                        "timezone": "Europe/London",
                        "jobTitle": "regional manager",
                        "company": "SkyPower",
                        "callCount": 0,
                        "lastContacted": null,
                        "lastOutcome": null,
                        "email": "me@email.com"
                    },
                    {
                        "id": "5502c598a6427fe74caa6def",
                        "userRef" : "youruserid2",
                        "firstName": "Jane",
                        "lastName": "Doe",
                        "valid": true,
                        "phoneCountryCode": "GB",
                        "phoneNumber": "07891011122",
                        "timezone": "Europe/London",
                        "jobTitle": "regional manager",
                        "company": "SkyPower",
                        "callCount": 1,
                        "lastContacted": "2015-03-13T11:10:16.981Z",
                        "lastOutcome": 7,
                        "email": "me@email.com"
                    }
                ]
            }

## Contact by ID [/Contact/id/{id}]

Access a contact using a CallSquad id.

+ Parameters
    + id (required, string, `5502c598a6427fe74caa6def`) ... The ID of the contact from callsquad.


### Get Contact [GET]


+ Request (application/json)

    + Headers

            Authorization: Bearer someRandomAccessToken

+ Response 200 (application/json)

    + Body

            {
                "id": "5502c598a6427fe74caa6def",
                "userRef" : "youruserid",
                "firstName": "Jane",
                "lastName": "Doe",
                "valid": true,
                "phoneCountryCode": "GB",
                "phoneNumber": "07891011122",
                "timezone": "Europe/London",
                "jobTitle": "regional manager",
                "company": "SkyPower",
                "callCount": 1,
                "lastContacted": "2015-03-13T11:10:16.981Z",
                "lastOutcome": 7,
                "email": "me@email.com"
            }

### Delete Contact [DELETE]


+ Request (application/json)

    + Headers

            Authorization: Bearer someRandomAccessToken

+ Response 200 (application/json)

    + Body

            {
                "message": "Delete sucessful"
            }
## Contact by userRef [/Contacts/userRef/{userRef}]
Access a contact using your userRef.

+ Parameters
    + userRef (required, string, `youruserid2`) ... The userRef you gave the contact.


### Get Contact [GET]


+ Request (application/json)

    + Headers

            Authorization: Bearer someRandomAccessToken

+ Response 200 (application/json)

    + Body

            {
                "id": "5502c598a6427fe74caa6def",
                "userRef" : "youruserid",
                "firstName": "Jane",
                "lastName": "Doe",
                "valid": true,
                "phoneCountryCode": "GB",
                "phoneNumber": "07891011122",
                "timezone": "Europe/London",
                "jobTitle": "regional manager",
                "company": "SkyPower",
                "callCount": 1,
                "lastContacted": "2015-03-13T11:10:16.981Z",
                "lastOutcome": 7,
                "email": "me@email.com"
            }

### Delete Contact [DELETE]


+ Request (application/json)

    + Headers

            Authorization: Bearer someRandomAccessToken

+ Response 200 (application/json)

    + Body

            {
                "message": "Delete sucessful"
            }

